#requires -Version 7.0
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$pipeline=Join-Path $PSScriptRoot 'Invoke-FairiesWritePipeline.ps1'
$schemaRoot=Join-Path $repoRoot 'docs\ai_team\schemas'
$temporaryRoot=Join-Path ([IO.Path]::GetTempPath()) ("fairies-phase3b-test-"+[Guid]::NewGuid().ToString('N'))
$reviewArtifactRoot='C:\Users\sakag\AppData\Local\Temp\fairies-phase3b-correction-001'
$approvedInputRoot='C:\Users\sakag\other\fairies-ai-runs\20260902T152525797Z-ad9a6de91e7d47039e0bcc1ffa0d6ed0'
$utf8=[Text.UTF8Encoding]::new($false)
$passed=[Collections.Generic.List[string]]::new()
function Assert($Value,[string]$Message){if(-not$Value){throw "ASSERTION_FAILED: $Message"}}
function WriteText([string]$Path,[string]$Text){[void][IO.Directory]::CreateDirectory((Split-Path $Path -Parent));[IO.File]::WriteAllText($Path,$Text,$utf8)}
function Git([string]$Repo,[string[]]$GitArguments){$o=& git.exe -C $Repo @GitArguments 2>&1;if($LASTEXITCODE){throw "fixture git failed: $o"};($o-join"`n").Trim()}
function NewRepo([string]$Name,[string]$Branch){$p=Join-Path $temporaryRoot $Name;[void][IO.Directory]::CreateDirectory($p);[void](Git $p @('init','--initial-branch',$Branch));[void](Git $p @('config','user.name','fixture'));[void](Git $p @('config','user.email','fixture@example.invalid'));WriteText (Join-Path $p 'base.txt') 'base';[void](Git $p @('add','base.txt'));$oldAuthor=$env:GIT_AUTHOR_DATE;$oldCommitter=$env:GIT_COMMITTER_DATE;try{$env:GIT_AUTHOR_DATE='2000-01-01T00:00:00Z';$env:GIT_COMMITTER_DATE='2000-01-01T00:00:00Z';[void](Git $p @('commit','-m','base'))}finally{$env:GIT_AUTHOR_DATE=$oldAuthor;$env:GIT_COMMITTER_DATE=$oldCommitter};$p}
function Agent([string]$Id,[string]$Repo,[string]$Mode='WRITE',[string]$Disposition='RUN',[string[]]$Deps=@(),[object[]]$Tests=@()){$allowed=[string[]]@();if($Disposition-ceq'RUN'-and$Mode-ceq'WRITE'){$allowed=[string[]]@('allowed.txt')};@{agent_id=$Id;disposition=$Disposition;worktree_absolute_path=$Repo;git_top_level=$Repo;branch=(Git $Repo @('branch','--show-current'));expected_head=(Git $Repo @('rev-parse','HEAD'));run_mode=$Mode;allowed_files=$allowed;forbidden_files=[string[]]@('secret.txt');instructions=$(if($Disposition-ceq'RUN'){'fixture'}else{''});test_commands=[object[]]$Tests;dependencies=[string[]]$Deps}}
function SaveInputs($Brief,[string]$Name){$d=Join-Path $temporaryRoot $Name;[void][IO.Directory]::CreateDirectory($d);$bp=Join-Path $d 'brief.json';WriteText $bp ($Brief|ConvertTo-Json -Depth 30);$sha=(Get-FileHash -Algorithm SHA256 $bp).Hash.ToLowerInvariant();$ap=Join-Path $d 'approval.json';WriteText $ap (@{schema_version='1.0';task_id=$Brief.task_id;verdict='APPROVE';task_brief_sha256=$sha}|ConvertTo-Json -Compress);@($bp,$ap)}
function LatestRun([string]$Root){Get-ChildItem -LiteralPath $Root -Directory|Sort-Object Name|Select-Object -Last 1}
function FileRecord([string]$Root,[IO.FileInfo]$File){[ordered]@{path=[IO.Path]::GetRelativePath($Root,$File.FullName).Replace('\','/');size=[long]$File.Length;sha256=(Get-FileHash -LiteralPath $File.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}}
function AssertInventory([string]$Root){
 $inventoryPath=Join-Path $Root 'artifact-inventory.json';$expected=@(Get-ChildItem -LiteralPath $Root -File -Recurse|Where-Object{-not$_.FullName.Equals($inventoryPath,[StringComparison]::OrdinalIgnoreCase)}|Sort-Object FullName|ForEach-Object{FileRecord $Root $_});$actual=@(Get-Content -Raw -LiteralPath $inventoryPath|ConvertFrom-Json)
 Assert ($actual.Count-eq$expected.Count) 'inventory missing or extra entry'
 for($i=0;$i-lt$expected.Count;$i++){Assert ($actual[$i].path-ceq$expected[$i].path) 'inventory path mismatch';Assert ([long]$actual[$i].size-eq$expected[$i].size) 'inventory size mismatch';Assert ($actual[$i].sha256-ceq$expected[$i].sha256) 'inventory digest mismatch';Assert (-not[IO.Path]::IsPathFullyQualified($actual[$i].path)) 'inventory absolute path';Assert ($actual[$i].path-notmatch'(^|/)\.\.(/|$)') 'inventory path escape'}
}
function PersistReviewArtifacts([IO.DirectoryInfo]$ReadyRun,[IO.DirectoryInfo]$BlockedRun){
 $resolved=[IO.Path]::GetFullPath($reviewArtifactRoot);$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());Assert ($resolved.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase)) 'review artifact root outside temp';Assert ([IO.Path]::GetFileName($resolved)-ceq'fairies-phase3b-correction-001') 'unexpected review artifact root'
 if([IO.Directory]::Exists($resolved)){Get-ChildItem -LiteralPath $resolved -Force|Remove-Item -Recurse -Force}else{[void][IO.Directory]::CreateDirectory($resolved)}
 Copy-Item -LiteralPath $ReadyRun.FullName -Destination (Join-Path $resolved 'runtime-ready') -Recurse
 Copy-Item -LiteralPath $BlockedRun.FullName -Destination (Join-Path $resolved 'runtime-blocked') -Recurse
 [IO.File]::WriteAllBytes((Join-Path $resolved 'approved-task-brief.txt'),[IO.File]::ReadAllBytes((Join-Path $approvedInputRoot 'task-brief.txt')))
 [IO.File]::WriteAllBytes((Join-Path $resolved 'human-approval.json'),[IO.File]::ReadAllBytes((Join-Path $approvedInputRoot 'human-approval.json')))
 Copy-Item -Path (Join-Path $schemaRoot 'phase3b-*.schema.json') -Destination $resolved
 $output=@("Phase 3B runtime harness passed $($passed.Count) groups")+@($passed|ForEach-Object{"PASS: $_"});WriteText (Join-Path $resolved 'harness-stdout.txt') ($output-join"`r`n");[IO.File]::WriteAllBytes((Join-Path $resolved 'harness-stderr.txt'),[byte[]]@())
 WriteText (Join-Path $resolved 'harness-evidence.json') (@{executable='pwsh';argv=@('-NoProfile','-NonInteractive','-File','scripts/ai_team/Test-FairiesWritePipeline.ps1');working_directory=$repoRoot;exit_code=0;timed_out=$false;production_codex=$false;network=$false;external_services=$false;android=$false;google_drive=$false}|ConvertTo-Json -Depth 10)
 $restoreRoot=Join-Path $temporaryRoot 'restore';[void][IO.Directory]::CreateDirectory($restoreRoot);$metadata=Get-Content -Raw (Join-Path $resolved 'runtime-ready/backend-change-metadata.json')|ConvertFrom-Json;$restoredRepo=Join-Path $restoreRoot 'repo';Copy-Item -LiteralPath $r1 -Destination $restoredRepo -Recurse;[void](Git $restoredRepo @('reset','--hard',$metadata.baseline_sha));foreach($entry in @($metadata.untracked)){$target=Join-Path $restoredRepo $entry.path;[void][IO.Directory]::CreateDirectory((Split-Path $target -Parent));[IO.File]::WriteAllBytes($target,[IO.File]::ReadAllBytes((Join-Path $resolved "runtime-ready/$($entry.artifact)")));Assert ((Get-FileHash $target -Algorithm SHA256).Hash.ToLowerInvariant()-ceq$entry.sha256) 'untracked restore digest'}
 $patchPath=Join-Path $resolved 'runtime-ready/backend-tracked.patch';if((Get-Item $patchPath).Length){& git.exe -C $restoredRepo apply --binary $patchPath;if($LASTEXITCODE){throw 'tracked patch restore failed'}};$restored=@(Git $restoredRepo @('status','--porcelain=v1','--untracked-files=all'));Assert ($restored-match'allowed.txt') 'restored change missing';WriteText (Join-Path $resolved 'restoration-verification.json') (@{result='PASS';agent='backend';changed_state=$restored}|ConvertTo-Json)
 $schemaResults=[Collections.Generic.List[object]]::new();foreach($id in @('backend','flutter','test_review')){foreach($kind in @('runtime-ready','runtime-blocked')){$path=Join-Path $resolved "$kind/$id-status.json";if(Test-Path $path){$valid=(Get-Content -Raw $path|Test-Json -SchemaFile (Join-Path $resolved 'phase3b-agent-status.schema.json'));Assert $valid "$kind $id status schema";$schemaResults.Add(@{path="$kind/$id-status.json";valid=$true})}}};foreach($kind in @('runtime-ready','runtime-blocked')){$path=Join-Path $resolved "$kind/result-manifest.json";$valid=(Get-Content -Raw $path|Test-Json -SchemaFile (Join-Path $resolved 'phase3b-result-manifest.schema.json'));Assert $valid "$kind manifest schema";$schemaResults.Add(@{path="$kind/result-manifest.json";valid=$true})};foreach($id in @('backend','flutter')){$path=Join-Path $resolved "runtime-ready/$id-report.json";$valid=(Get-Content -Raw $path|Test-Json -SchemaFile (Join-Path $resolved 'phase3b-implementation-report.schema.json'));Assert $valid "$id report schema";$schemaResults.Add(@{path="runtime-ready/$id-report.json";valid=$true})};$reviewPath=Join-Path $resolved 'runtime-ready/test_review-report.json';$valid=(Get-Content -Raw $reviewPath|Test-Json -SchemaFile (Join-Path $resolved 'phase3b-write-review-report.schema.json'));Assert $valid 'WRITE review report schema';$schemaResults.Add(@{path='runtime-ready/test_review-report.json';valid=$true});WriteText (Join-Path $resolved 'schema-verification.json') (@($schemaResults)|ConvertTo-Json)
 $inventoryPath=Join-Path $resolved 'artifact-inventory.json';$inventory=@(Get-ChildItem -LiteralPath $resolved -File -Recurse|Where-Object{-not$_.FullName.Equals($inventoryPath,[StringComparison]::OrdinalIgnoreCase)}|Sort-Object FullName|ForEach-Object{FileRecord $resolved $_});WriteText $inventoryPath ($inventory|ConvertTo-Json -Depth 10);AssertInventory $resolved
}
function InvokeScenario($Brief,[string]$Name,[string]$Behavior='success',[int]$Timeout=10,[switch]$ExpectFailure){foreach($repo in @($r1,$r2)){if($repo){$fixtureChange=Join-Path $repo 'allowed.txt';if(Test-Path -LiteralPath $fixtureChange){Remove-Item -LiteralPath $fixtureChange -Force}}};$paths=SaveInputs $Brief $Name;$runs=Join-Path $temporaryRoot "runs-$Name";$env:F3B_FIXTURE_BEHAVIOR=$Behavior;$env:F3B_FIXTURE_MARKERS=Join-Path $temporaryRoot "markers-$Name";[void][IO.Directory]::CreateDirectory($env:F3B_FIXTURE_MARKERS);$failed=$false;try{& $pipeline -TaskBriefPath $paths[0] -ApprovalPath $paths[1] -RunsRoot $runs -CodexExecutable pwsh -CodexPrefixArgument @('-NoProfile','-NonInteractive','-File',(Join-Path $temporaryRoot 'codex-stub.ps1')) -AgentTimeoutSeconds $Timeout|Out-Null}catch{$failed=$true;if(-not$ExpectFailure){throw}};Assert ($failed-eq[bool]$ExpectFailure) "$Name expected failure mismatch";LatestRun $runs}
try{
 [void][IO.Directory]::CreateDirectory($temporaryRoot)
 $tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($pipeline,[ref]$tokens,[ref]$errors);Assert ($errors.Count-eq0) 'runtime parser errors'
 foreach($schema in Get-ChildItem $schemaRoot 'phase3b-*.schema.json'){Get-Content -Raw $schema.FullName|ConvertFrom-Json -Depth 40|Out-Null};$passed.Add('PowerShell and JSON parse')
 . $pipeline -LibraryOnly
 foreach($bad in @('..\x','C:\x','a:b','*.txt','.')){try{Assert-F3BRelativePath $bad;throw 'accepted'}catch{Assert ($_.Exception.Message-notmatch'accepted') "unsafe path $bad"}};$passed.Add('relative path, ADS, glob, absolute and dot rejection')
 $r1=NewRepo backend 'agent/backend';$r2=NewRepo flutter 'agent/flutter';$rr=NewRepo review 'agent/test-review'
 $testScript=Join-Path $temporaryRoot 'test-ok.ps1';WriteText $testScript "exit 0";$test=@(@{command_id='fixed';executable='pwsh';argv=@('-NoProfile','-NonInteractive','-File',$testScript);working_directory=$r1;timeout_seconds=10;network=$false;external_service=$false;device=$false})
 $stub=@'
param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Rest)
$inputText=[Console]::In.ReadToEnd();$p=$inputText|ConvertFrom-Json -Depth 50
[IO.File]::WriteAllText((Join-Path $env:F3B_FIXTURE_MARKERS ("$($p.agent_id)-start")),[DateTime]::UtcNow.ToString('o'))
if($p.role-eq'IMPLEMENTATION'){Start-Sleep -Milliseconds 700}
if($p.role-eq'IMPLEMENTATION'-and$p.agent_id-eq'backend'-and$env:F3B_FIXTURE_BEHAVIOR-notin @('partial_fail','timeout','sequential_fail')){[IO.File]::WriteAllBytes((Join-Path $p.worktree 'allowed.txt'),[byte[]](0,1,2,10,13,255))}
if($env:F3B_FIXTURE_BEHAVIOR-eq'timeout'-and$p.agent_id-eq'backend'){Start-Sleep 3}
if($env:F3B_FIXTURE_BEHAVIOR-eq'partial_fail'-and$p.agent_id-eq'backend'){exit 7}
if($env:F3B_FIXTURE_BEHAVIOR-eq'sequential_fail'-and$p.agent_id-eq'backend'){exit 8}
if($p.role-eq'IMPLEMENTATION'){$claims=@($p.test_commands|ForEach-Object{@{command_id=$_.command_id;exit_code=0;timed_out=$false}});$changed=@();if($p.agent_id-eq'backend'-and$env:F3B_FIXTURE_BEHAVIOR-notin @('partial_fail','timeout','sequential_fail')){$changed=@('allowed.txt')};$report=@{schema_version='1.0';task_id=$p.task_id;agent_id=$p.agent_id;status=$(if($env:F3B_FIXTURE_BEHAVIOR-eq'blocked_report'){'BLOCKED'}else{'SUCCESS'});observed_worktree=$p.worktree;observed_git_top_level=$p.git_top_level;observed_branch=$p.branch;pre_head=$p.pre_head;post_head=$p.pre_head;summary='fixture';claimed_changed_files=$changed;staged_files=@();test_claims=$claims;unverified_items=@()}}
else{$findings=[object[]]@();if($env:F3B_FIXTURE_BEHAVIOR-eq'review_reject'){$findings=[object[]]@(@{severity='MAJOR';location='fixture';reproduction_condition='fixture';expected_result='pass'})};$report=@{schema_version='1.0';task_id=$p.task_id;reviewer_agent_id='test_review';review_type='WRITE_RUNTIME';reviewed_agent_ids=[string[]]@('backend','flutter');reviewed_artifact_sha256=$p.fixed_delivery.change_bundle.sha256;reviewed_schema_sha256=$p.fixed_delivery.schemas;acceptance_criteria_results=[object[]]@(@{criterion='runtime';result=$(if($env:F3B_FIXTURE_BEHAVIOR-eq'review_reject'){'FAIL'}else{'PASS'})});findings=$findings;unverified_items=[string[]]@();review_verdict=$(if($env:F3B_FIXTURE_BEHAVIOR-eq'review_reject'){'REQUEST_CHANGES'}else{'APPROVE'});final_result=$(if($env:F3B_FIXTURE_BEHAVIOR-eq'review_reject'){'BLOCKED'}else{'READY_FOR_PHASE3C'})}}
$outIndex=[Array]::IndexOf($Rest,'--output-last-message');$out=$Rest[$outIndex+1];[IO.File]::WriteAllText($out,($report|ConvertTo-Json -Depth 50),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $env:F3B_FIXTURE_MARKERS ("$($p.agent_id)-end")),[DateTime]::UtcNow.ToString('o'));exit 0
'@;WriteText (Join-Path $temporaryRoot 'codex-stub.ps1') $stub
 $parallel=@{schema_version='1.0';task_id='parallel';baseline_sha=(Git $r1 @('rev-parse','HEAD'));execution_strategy='PARALLEL';sequential_order=@();agents=@((Agent backend $r1 'WRITE' 'RUN' @() $test),(Agent flutter $r2),(Agent test_review $rr 'READ_ONLY'))}
 function AssertEarlyBlocked([IO.DirectoryInfo]$Run,[string]$Reason,[string]$Markers){$manifestPath=Join-Path $Run.FullName 'result-manifest.json';$manifest=Get-Content -Raw $manifestPath|ConvertFrom-Json;Assert ($manifest.final_result-ceq'BLOCKED') "$Reason blocked manifest";Assert ($manifest.stage-ceq'INPUT_VALIDATION') "$Reason stage";Assert ($manifest.reason_code-ceq$Reason) "$Reason reason";Assert ((Get-Content -Raw $manifestPath)|Test-Json -SchemaFile (Join-Path $Run.FullName 'schemas/phase3b-result-manifest.schema.json')) "$Reason manifest schema";foreach($id in @('backend','flutter','test_review')){$statusPath=Join-Path $Run.FullName "$id-status.json";$status=Get-Content -Raw $statusPath|ConvertFrom-Json;Assert (-not$status.started) "$Reason started $id";Assert ($status.reason_code-ceq$Reason) "$Reason status reason $id";Assert ((Get-Content -Raw $statusPath)|Test-Json -SchemaFile (Join-Path $Run.FullName 'schemas/phase3b-agent-status.schema.json')) "$Reason status schema $id"};Assert (@(Get-ChildItem -LiteralPath $Markers -File).Count-eq0) "$Reason worker started"}
 $approvalPaths=SaveInputs $parallel 'approval-mismatch';WriteText $approvalPaths[1] (@{schema_version='1.0';task_id=$parallel.task_id;verdict='APPROVE';task_brief_sha256=('0'*64)}|ConvertTo-Json -Compress);$approvalRuns=Join-Path $temporaryRoot 'runs-approval-mismatch';$approvalMarkers=Join-Path $temporaryRoot 'markers-approval-mismatch';[void][IO.Directory]::CreateDirectory($approvalMarkers);$env:F3B_FIXTURE_MARKERS=$approvalMarkers;try{& $pipeline -TaskBriefPath $approvalPaths[0] -ApprovalPath $approvalPaths[1] -RunsRoot $approvalRuns -CodexExecutable pwsh -CodexPrefixArgument @('-NoProfile','-NonInteractive','-File',(Join-Path $temporaryRoot 'codex-stub.ps1')) -AgentTimeoutSeconds 10|Out-Null;throw 'approval mismatch accepted'}catch{Assert ($_.Exception.Message-notmatch'accepted') 'approval mismatch accepted'};AssertEarlyBlocked (LatestRun $approvalRuns) 'APPROVAL_MISMATCH' $approvalMarkers;$passed.Add('runtime approval mismatch BLOCKED evidence without worker start')
 $dependency=$parallel|ConvertTo-Json -Depth 30|ConvertFrom-Json -Depth 30;$dependency.task_id='dependency-plan';$dependency.agents[0].dependencies=@('flutter');$dependencyRun=InvokeScenario $dependency 'dependency-plan' 'success' 10 -ExpectFailure;AssertEarlyBlocked $dependencyRun 'PARALLEL_PLAN_INVALID' $env:F3B_FIXTURE_MARKERS;$passed.Add('runtime dependency-plan failure BLOCKED evidence without worker start')
 $run=InvokeScenario $parallel 'success';$manifest=Get-Content -Raw (Join-Path $run.FullName 'result-manifest.json')|ConvertFrom-Json;Assert ($manifest.final_result-ceq'READY_FOR_PHASE3C') 'READY manifest';foreach($s in Get-ChildItem (Join-Path $run.FullName 'schemas') '*.json'){Get-Content -Raw $s.FullName|ConvertFrom-Json -Depth 40|Out-Null};foreach($id in @('backend','flutter','test_review')){Assert ((Get-Content -Raw (Join-Path $run.FullName "$id-status.json"))|Test-Json -SchemaFile (Join-Path $run.FullName 'schemas/phase3b-agent-status.schema.json')) "$id status invalid"};Assert (Test-Path (Join-Path $run.FullName 'artifact-inventory.json')) 'inventory missing';Assert (Test-Path (Join-Path $run.FullName 'backend-tracked.patch')) 'patch missing';$passed.Add('runtime success, artifact delivery, schemas, READY manifest')
 $bs=[datetime](Get-Content (Join-Path $env:F3B_FIXTURE_MARKERS 'backend-start'));$fs=[datetime](Get-Content (Join-Path $env:F3B_FIXTURE_MARKERS 'flutter-start'));$be=[datetime](Get-Content (Join-Path $env:F3B_FIXTURE_MARKERS 'backend-end'));$fe=[datetime](Get-Content (Join-Path $env:F3B_FIXTURE_MARKERS 'flutter-end'));Assert (($fs-lt$be)-and($bs-lt$fe)) 'workers did not overlap';$passed.Add('true parallel start before collection')
 $representativeBlocked=$null;foreach($case in @('partial_fail','timeout','blocked_report','review_reject')){$timeout=if($case-eq'timeout'){1}else{10};$bad=InvokeScenario $parallel $case $case $timeout -ExpectFailure;if($case-eq'blocked_report'){$representativeBlocked=$bad};$m=Get-Content -Raw (Join-Path $bad.FullName 'result-manifest.json')|ConvertFrom-Json;Assert ($m.final_result-ceq'BLOCKED') "$case blocked manifest";Assert ((Get-Content -Raw (Join-Path $bad.FullName 'result-manifest.json'))|Test-Json -SchemaFile (Join-Path $bad.FullName 'schemas/phase3b-result-manifest.schema.json')) "$case manifest schema"};$passed.Add('partial failure collection, timeout, report mismatch and review rejection')
 $sequential=$parallel.Clone();$sequential.task_id='sequential';$sequential.execution_strategy='SEQUENTIAL';$sequential.sequential_order=@('backend','flutter');$sequential.agents[1].dependencies=@('backend');$bad=InvokeScenario $sequential 'sequential' 'sequential_fail' 10 -ExpectFailure;Assert (-not(Test-Path (Join-Path $env:F3B_FIXTURE_MARKERS 'flutter-start'))) 'sequential successor started';$passed.Add('sequential fail-stop marker')
 $cycle=$sequential|ConvertTo-Json -Depth 30|ConvertFrom-Json -Depth 30;$cycle.agents[0].dependencies=@('flutter');try{Assert-F3BPlan $cycle;throw 'accepted'}catch{Assert ($_.Exception.Message-notmatch'accepted') 'dependency cycle accepted'};$skip=$parallel|ConvertTo-Json -Depth 30|ConvertFrom-Json -Depth 30;$skip.agents[1].disposition='SKIP';$skip.agents[1].allowed_files=@();$skip.agents[0].dependencies=@('flutter');try{Assert-F3BPlan $skip;throw 'accepted'}catch{Assert ($_.Exception.Message-notmatch'accepted') 'SKIP dependency accepted'};$passed.Add('dependency cycle and SKIP dependency rejection')
 $paths=SaveInputs $parallel 'digest';WriteText $paths[0] ((Get-Content -Raw $paths[0])+' ');try{Assert-F3BInputGate $paths[0] $paths[1] ('a'*64) parallel;throw 'accepted'}catch{Assert ($_.Exception.Message-notmatch'accepted') 'digest mutation accepted'};$passed.Add('per-start digest and approval gate')
 if($IsWindows){$outside=Join-Path $temporaryRoot outside;[void][IO.Directory]::CreateDirectory($outside);$link=Join-Path $r1 link;cmd /c mklink /J $link $outside|Out-Null;try{Get-F3BPhysicalPath (Join-Path $link 'x')|Out-Null;Assert (-not(Test-F3BInside (Get-F3BPhysicalPath $link) (Get-F3BPhysicalPath $r1))) 'junction escape invisible'}finally{[IO.Directory]::Delete($link)}};$passed.Add('physical junction boundary')
 PersistReviewArtifacts $run $representativeBlocked
 "Phase 3B runtime harness passed $($passed.Count) groups";$passed|ForEach-Object{"PASS: $_"}
}finally{Remove-Item Env:F3B_FIXTURE_BEHAVIOR,Env:F3B_FIXTURE_MARKERS -ErrorAction SilentlyContinue;if([IO.Directory]::Exists($temporaryRoot)){$full=[IO.Path]::GetFullPath($temporaryRoot);$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if(-not$full.StartsWith($base,[StringComparison]::OrdinalIgnoreCase)-or-not[IO.Path]::GetFileName($full).StartsWith('fairies-phase3b-test-',[StringComparison]::Ordinal)){throw 'unsafe cleanup'};Remove-Item -LiteralPath $full -Recurse -Force}}
